### ISSUE TITLE
wrong number of arguments (given 3, expected 1..2)

### ISSUE THREAD

**Issue by willywutang** [agardiner/csv-diff-report#16]
I'm running into this error when using csvdiff, and wondering if you could help resolve it?

> csvdiff a.csv b.csv 
Performing file diff:
  From File:    a.csv
  To File:      b.csv
Opening FROM file 'a.csv'...
An error occurred opening file a.csv: wrong number of arguments (given 3, expected 1..2)
/usr/local/Cellar/ruby/3.0.0/lib/ruby/3.0.0/csv.rb:1412:in `open': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-0.6.1/lib/csv-diff/csv_source.rb:60:in `initialize'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/report.rb:262:in `new'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/report.rb:262:in `open_source'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/report.rb:219:in `diff_file'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/report.rb:87:in `diff'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/cli.rb:131:in `process'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/lib/csv-diff-report/cli.rb:101:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/csv-diff-report-0.3.6/bin/csvdiff:7:in `<top (required)>'
	from /usr/local/bin/csvdiff:23:in `load'
	from /usr/local/bin/csvdiff:23:in `<main>'

**Comment by megahall** [comment]
Fix available in https://github.com/agardiner/csv-diff/issues/17 and https://github.com/megahall/csv-diff/pull/1 .
